name: Lint Posts

on:
  push:
    branches:
      - '**'  # Runs on pushes to all branches
  pull_request:
    branches:
      - 'gh-pages'  # Runs when a PR targets the gh-pages branch

jobs:
    lint-posts:
        runs-on: "ubuntu-latest"
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                node-version: 20.x
                cache: npm
            - name: Run install
              uses: borales/actions-yarn@v5.0.0
              with:
                cmd: install
            - name: Run lint
              uses: borales/actions-yarn@v5.0.0
              with:
                cmd: lint
